-- Word lists for typeinc. Lowercase a-z only (engine has no layout-aware
-- text input, so accented characters can't be typed).
return {
  es = {
    "casa", "perro", "gato", "tiempo", "mundo", "agua", "fuego", "tierra",
    "viento", "cielo", "luna", "libro", "mesa", "silla", "puerta", "ventana",
    "camino", "ciudad", "campo", "flor", "hombre", "mujer", "amigo", "amiga",
    "familia", "trabajo", "escuela", "palabra", "letra", "juego", "punto",
    "nube", "lluvia", "nieve", "calor", "noche", "tarde", "verano",
    "invierno", "tren", "barco", "coche", "calle", "plaza", "puente",
    "torre", "reloj", "papel", "color", "verde", "rojo", "azul", "blanco",
    "negro", "grande", "nuevo", "viejo", "bueno", "malo", "feliz", "triste",
    "fuerte", "cuerpo", "mano", "cabeza", "boca", "ojos", "pelo", "diente",
    "sangre", "hueso", "piel", "pierna", "brazo", "dedo", "comida", "pan",
    "leche", "queso", "carne", "fruta", "manzana", "naranja", "uva", "pera",
    "arroz", "huevo", "sal", "dulce", "amargo", "cocina", "plato", "vaso",
    "cuchara", "tenedor", "bosque", "monte", "lago", "playa", "arena",
    "piedra", "hierba", "hoja", "rama", "semilla", "animal", "caballo",
    "vaca", "cerdo", "oveja", "pollo", "pato", "pez", "ave", "hormiga",
    "abeja", "mosca", "tigre", "oso", "lobo", "zorro", "conejo", "tortuga",
    "canto", "baile", "fiesta", "regalo", "dinero", "tienda", "mercado",
    "precio", "banco", "salud", "cama", "luz", "sonido", "voz", "cuento",
  },
  en = {
    "time", "world", "house", "water", "fire", "earth", "wind", "sky",
    "moon", "star", "book", "table", "chair", "door", "window", "road",
    "city", "field", "flower", "tree", "man", "woman", "friend", "family",
    "work", "school", "word", "letter", "game", "point", "cloud", "rain",
    "snow", "cold", "heat", "night", "evening", "summer", "winter", "train",
    "boat", "car", "plane", "street", "bridge", "tower", "clock", "paper",
    "pencil", "color", "green", "red", "blue", "white", "black", "big",
    "new", "old", "good", "bad", "happy", "sad", "strong", "body", "hand",
    "head", "mouth", "eyes", "hair", "tooth", "heart", "blood", "bone",
    "skin", "leg", "arm", "finger", "food", "bread", "milk", "cheese",
    "meat", "fruit", "apple", "orange", "grape", "pear", "rice", "egg",
    "salt", "sweet", "kitchen", "plate", "glass", "spoon", "fork", "forest",
    "mountain", "river", "lake", "beach", "sand", "stone", "grass", "leaf",
    "branch", "root", "seed", "animal", "horse", "cow", "sheep", "chicken",
    "duck", "fish", "bird", "tiger", "bear", "wolf", "fox", "mouse",
    "rabbit", "turtle", "snake", "music", "dance", "party", "gift",
    "money", "shop", "market", "price", "health", "bed", "dream", "light",
    "sound", "voice", "story",
  },
}
